doc.

diff --git a/acrypt b/acrypt
--- a/acrypt
+++ b/acrypt
@@ -132,6 +132,14 @@ else
 fi
 
 
+# -- dep check
+
+if ! which openssl &>/dev/null; then
+    echo "Error: openssl not found"
+    exit 1
+fi
+
+
 # -- main
 
 if [[ $action = "generate" ]]; then
